const ACTIONS = {
  beg: {
    label: 'Mendigar',
    cooldownMs: 120000,
    successChance: 0.82,
    rewardMin: 120,
    rewardMax: 420,
    lossMin: 60,
    lossMax: 200,
    successText: 'Un random te dejó una propina.',
    failText: 'Te estafaron mientras pedías.',
  },
  crime: {
    label: 'Crimen',
    cooldownMs: 900000,
    successChance: 0.5,
    rewardMin: 700,
    rewardMax: 3200,
    lossMin: 400,
    lossMax: 1800,
    successText: 'El golpe salió perfecto.',
    failText: 'Te atraparon y pagaste multa.',
  },
  heist: {
    label: 'Atraco',
    cooldownMs: 1200000,
    successChance: 0.42,
    rewardMin: 900,
    rewardMax: 4500,
    lossMin: 700,
    lossMax: 2600,
    successText: 'Robaste un botín jugoso.',
    failText: 'Te descubrieron y perdiste plata.',
  },
  search: {
    label: 'Buscar',
    cooldownMs: 300000,
    successChance: 0.7,
    rewardMin: 250,
    rewardMax: 1200,
    lossMin: 120,
    lossMax: 650,
    successText: 'Encontraste monedas tiradas.',
    failText: 'No encontraste nada y gastaste en el camino.',
  },
  fish: {
    label: 'Pescar',
    cooldownMs: 420000,
    successChance: 0.66,
    rewardMin: 300,
    rewardMax: 1600,
    lossMin: 150,
    lossMax: 700,
    successText: 'Vendiste una pesca premium.',
    failText: 'Se rompió el equipo y pagaste arreglo.',
  },
  mine: {
    label: 'Minar',
    cooldownMs: 480000,
    successChance: 0.62,
    rewardMin: 450,
    rewardMax: 1900,
    lossMin: 180,
    lossMax: 900,
    successText: 'Sacaste minerales valiosos.',
    failText: 'Herramientas dañadas, tocó pagar.',
  },
  hunt: {
    label: 'Cazar',
    cooldownMs: 420000,
    successChance: 0.63,
    rewardMin: 350,
    rewardMax: 1500,
    lossMin: 170,
    lossMax: 750,
    successText: 'Cacería exitosa, buen pago.',
    failText: 'Gastaste en equipo y no salió nada.',
  },
  dig: {
    label: 'Excavar',
    cooldownMs: 300000,
    successChance: 0.65,
    rewardMin: 260,
    rewardMax: 1400,
    lossMin: 140,
    lossMax: 700,
    successText: 'Encontraste un cofre escondido.',
    failText: 'Solo encontraste basura y perdiste plata.',
  },
  freelance: {
    label: 'Freelance',
    cooldownMs: 600000,
    successChance: 0.74,
    rewardMin: 500,
    rewardMax: 2100,
    lossMin: 220,
    lossMax: 900,
    successText: 'Cliente satisfecho, te pagó bien.',
    failText: 'El cliente rechazó el trabajo y perdiste tiempo/plata.',
  },
  invest: {
    label: 'Invertir',
    cooldownMs: 1200000,
    successChance: 0.46,
    rewardMin: 900,
    rewardMax: 4200,
    lossMin: 500,
    lossMax: 2600,
    successText: 'La inversión explotó para arriba.',
    failText: 'El mercado se cayó y perdiste.',
  },
};

function getIncomeAction(name) {
  return ACTIONS[String(name || '').toLowerCase()] || null;
}

function listIncomeActions() {
  return Object.entries(ACTIONS).map(([key, value]) => ({ key, ...value }));
}

module.exports = {
  getIncomeAction,
  listIncomeActions,
};
